# Site
name: "Synaptic Machine"
title: "Synaptic Machine"
description: "Synaptic Machine is a research-backed blog exploring the world of artificial intelligence. My goal is to connect curious minds with original and ground-breaking research shaping the future of AI. Each post is designed to be rooted in peer-reviewed research, accessible to early-career AI enthusiasts and packed with credible references. 
Where you’re building your first model or just want to understand what the AI hype is all about, this blog is a place for you to think, learn and explore
"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""  
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Fathima Afreen
    display_name: Fathima Afreen
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: afreen.iws@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Synaptic Machine. I read research papers (so you don’t have to), break them down and share insights that are grounded in evidence, not just vibes."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
